
[build]
  command = "npm run build"
  commandOrigin = "config"
  environment= "NODE_VERSION=10"
  publish = "public"
  publishOrigin = "config"

[plugins]
  - inputs= {}
    origin = "ui"
    package = "'@netlify/plugin-lighthouse'"
  - inputs= {}
    origin = "config"
    package = "netlify-plugin-gatsby-cache"
