
[build]
  command = "npm run build"
  commandOrigin = "config"
  environment= "NODE_VERSION=10"
  publish = "public"
  publishOrigin = "config"

[plugins]
  origin = "ui"
  package = "'@netlify/plugin-lighthouse'"
  origin = "config"
  package = "netlify-plugin-gatsby-cache"
