build:
  command = npm run build
  commandOrigin: config
  environment:
    - NODE_VERSION
  publish: /opt/build/repo/public
  publishOrigin: config

plugins:
  - inputs: {}
    origin: ui
    package: '@netlify/plugin-lighthouse'
  - inputs: {}
    origin: config
    package: netlify-plugin-gatsby-cache
