
[build]
  command = "npm run build"
  commandOrigin = "config"
  environment= "NODE_VERSION=10"
  publish = "public"
  publishOrigin = "config"

[[plugins]]
  package = "'@netlify/plugin-lighthouse'"
  package = "netlify-plugin-gatsby-cache"
